# Generated by Django 4.2.4 on 2023-08-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='DomainName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
