# Generated by Django 4.2.4 on 2023-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_webinfo_domainname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='DomainName',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
