# Generated by Django 4.2.4 on 2023-08-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_webinfo_domainname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinfo',
            name='DomainName',
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
