# Generated by Django 4.2.4 on 2023-08-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_webinfo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(blank=True, max_length=10000, null=True)),
                ('AccessTime', models.DateTimeField()),
            ],
        ),
    ]
