# Generated by Django 4.2.4 on 2023-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(blank=True, null=True)),
                ('Y', models.IntegerField(blank=True, null=True)),
                ('page', models.CharField(blank=True, max_length=10000, null=True)),
                ('Time', models.DateTimeField()),
                ('Location', models.CharField(blank=True, default='None', max_length=100000, null=True)),
                ('Information', models.CharField(blank=True, default='None', max_length=1000000000, null=True)),
            ],
        ),
    ]
