# Generated by Django 4.2.4 on 2023-08-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_hover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XC', models.IntegerField(blank=True, null=True)),
                ('YC', models.IntegerField(blank=True, null=True)),
                ('pageC', models.CharField(blank=True, max_length=10000, null=True)),
                ('TimeC', models.DateTimeField()),
                ('LocationC', models.CharField(blank=True, default='None', max_length=100000, null=True)),
            ],
        ),
    ]
