# Generated by Django 4.2.4 on 2023-08-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_click_typec_hover_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Page', models.CharField(blank=True, max_length=10100101, null=True)),
                ('Other_Pages', models.CharField(blank=True, max_length=124124124, null=True)),
                ('FirstPageAccessTime', models.DateTimeField()),
            ],
        ),
    ]
