# Generated by Django 4.2.4 on 2023-08-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='userIPAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.webinfo'),
        ),
    ]
